spring:
    datasource:
        url: jdbc:h2:mem:courses-platform
        username: coursesplatform
        password:
    jpa:
        show_sql: true
        open-in-view: false
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                format_sql: true
    h2:
        console:
            enabled: true
            path: /h2-console
            settings:
                trace: false
                web-allow-other: false